### ISSUE TITLE
Backup Power Error

### ISSUE THREAD

**Issue by MockMicrobe** [fluffy-mods/BackupPower#1]
**Describe the bug**  

When the generator was supposed to kick on, it vanished and there was a repeating error message at the top of the screen, "Backup power control box destroyed because the generator is was attached to was destroyed." Except the control box wasn't destroyed, and can't be deconstructed either by a pawn or by debug commands.
**Expected behavior**  

The generator would turn on.
**Steps to reproduce**  

1. Install a control box on a wood burning generator.
2. Wait for the power to go below the limit.
3.

**Other mods**  

Oh boy, yes. But I had it installed at the very end of the mod load list.

**Output log**  

https://gist.github.com/8e91f35da8da081367aba45cc612983b

**Save game**  

[RimworldBugReportSave.zip](https://github.com/fluffy-mods/BackupPower/files/4576747/RimworldBugReportSave.zip)

**Screenshots**  

**Environment**  
 - OS:  Windows 10
 - 32/64 bits  64 bit
 
**Game**
 - 32/64 bits - 64 bit
 - Steam/DRM free - Steam
 - Version 1.1.2618

**Comment by FluffierThanThou** [comment]
zube bot got a bit excited there, but I did try to fix the problem. Not entirely sure why your version entered a failure state, but at least now it should be able to recover. I'd love to hear about any further weirdness.
