### ISSUE TITLE
Doesn't work during a solar flare ss planned. 

### ISSUE THREAD

**Issue by LuciferZ25** [fluffy-mods/BackupPower#14]
As it says in the title. I set the large power gen from rimefeller to turn on when power is below 12% .but when a solar flare strikes, it doesn't start that thing up. If I start it manually, it behaves like any other equipment n doesn't produce power due to the solar flare.

**Comment by LuciferZ25** [comment]
Yup the RT solar shield has to remain active to protect this equipment. I suggest u to give it as an option instead of removing it out right. It's fun. If u don't react fast enough, u lose the day.

**Comment by FluffierThanThou** [comment]
this is pretty much as designed. 

The backup part of it should kick in when power is low for any reason, but if a solar flare fries electronics, it should also fry the backup control unit.
