### ISSUE TITLE
Is it possible to change "turn on / off at xx%"?

### ISSUE THREAD

**Issue by hasezoey** [fluffy-mods/BackupPower#27]
**Environment**  
 - OS: Linux
 - 32/64 bits: 64
 
**Game**
 - 32/64 bits: 64
 - Steam/DRM free: steam
 - Version: RimWorld 1.1.2654 rev674

Files: https://gist.github.com/hasezoey/7056ae81a9609215f626e3f581f27efc

---

as the title say, is it possible to change the "turn on when below xx% & turn off when above xx%"? when yes, i couldnt find the settings to change it

**Comment by FluffierThanThou** [comment]
the widget has interactive sliders ;). You're not the first to ask though,
so it appears I've tried to be a bit too clever. I'll see about adding some
better indication that it is interactive.

>

**Comment by hasezoey** [comment]
sorry to ask, but what is an "widget" in rimworld context? maybe the one like "uninstall"? - when yes, i already tried right & left click, with shift too and also dragging and nothing has done anything (left click only have an menu to copy the settings to all / room)

**Comment by FluffierThanThou** [comment]
![image](https://i.imgur.com/mg9oMSs.gif)

**Comment by hasezoey** [comment]
thanks for the gif, i didnt notice these two were slideres (because nothing else in rimworld uses this)

-> it would be nice if this gif would get added to the README

(closing because my question got answered)
